### ISSUE TITLE
Add aLt tExT gEnErAtOr

### ISSUE THREAD

**Issue by Rippr** [Rippr/DankBot#24]
Add a command that generates alT cAsEd tExT.

Trigger can be "alt: This is my text".

**Comment by Shellzz2112** [comment]
OkAy oN iT

**Comment by Shellzz2112** [comment]
**sInCe I Do NoT No HoW To AdD ThIs To Ur "hAnDlErS.Py" ThInG So Im JuSt SeNdInG 2 CoDeS, OnE WhIcH CoNsIdErS ExClUsIoN Of " " AnD OnE WhIcH DoEsNt.. DoNt KiLl Me FoR LaCk Of "eFfIcIeNcY". thIs WaS GeNeRaTeD WiTh ThE PrOgRaM ToO ;)**

[The Codes.txt](https://github.com/Rippr/DankBot/files/2566595/The.Codes.txt)
